// Static hotel database for autocomplete search
// Comprehensive list of popular hotels across US, Brazil, Europe and worldwide

export const hotels = [
  // === BRASIL - Rio de Janeiro ===
  { name: 'Copacabana Palace', destination: 'Rio de Janeiro, Brasil', stars: 5 },
  { name: 'Hotel Fasano Rio de Janeiro', destination: 'Rio de Janeiro, Brasil', stars: 5 },
  { name: 'Hilton Copacabana', destination: 'Rio de Janeiro, Brasil', stars: 5 },
  { name: 'JW Marriott Hotel Rio de Janeiro', destination: 'Rio de Janeiro, Brasil', stars: 5 },
  { name: 'Grand Hyatt Rio de Janeiro', destination: 'Rio de Janeiro, Brasil', stars: 5 },
  { name: 'Sheraton Grand Rio Hotel & Resort', destination: 'Rio de Janeiro, Brasil', stars: 5 },
  { name: 'Windsor Atlantica Hotel', destination: 'Rio de Janeiro, Brasil', stars: 4 },
  { name: 'Ibis Copacabana', destination: 'Rio de Janeiro, Brasil', stars: 3 },
  { name: 'Novotel Rio de Janeiro Botafogo', destination: 'Rio de Janeiro, Brasil', stars: 4 },
  { name: 'Hotel Negresco', destination: 'Rio de Janeiro, Brasil', stars: 3 },
  { name: 'Fairmont Rio de Janeiro', destination: 'Rio de Janeiro, Brasil', stars: 5 },
  { name: 'Miramar Hotel by Windsor', destination: 'Rio de Janeiro, Brasil', stars: 5 },
  { name: 'Hotel Emiliano Rio', destination: 'Rio de Janeiro, Brasil', stars: 5 },
  { name: 'Santa Teresa Hotel RJ - MGallery', destination: 'Rio de Janeiro, Brasil', stars: 5 },
  { name: 'Windsor Marapendi', destination: 'Rio de Janeiro, Brasil', stars: 4 },
  { name: 'Prodigy Santos Dumont', destination: 'Rio de Janeiro, Brasil', stars: 4 },
  // === BRASIL - Sao Paulo ===
  { name: 'Hotel Fasano Sao Paulo', destination: 'Sao Paulo, Brasil', stars: 5 },
  { name: 'Tivoli Mofarrej Sao Paulo', destination: 'Sao Paulo, Brasil', stars: 5 },
  { name: 'Grand Hyatt Sao Paulo', destination: 'Sao Paulo, Brasil', stars: 5 },
  { name: 'Renaissance Sao Paulo Hotel', destination: 'Sao Paulo, Brasil', stars: 5 },
  { name: 'Hotel Unique', destination: 'Sao Paulo, Brasil', stars: 5 },
  { name: 'Palacio Tangara', destination: 'Sao Paulo, Brasil', stars: 5 },
  { name: 'InterContinental Sao Paulo', destination: 'Sao Paulo, Brasil', stars: 5 },
  { name: 'Hilton Sao Paulo Morumbi', destination: 'Sao Paulo, Brasil', stars: 5 },
  { name: 'Melia Paulista', destination: 'Sao Paulo, Brasil', stars: 4 },
  { name: 'Ibis Paulista', destination: 'Sao Paulo, Brasil', stars: 3 },
  { name: 'Novotel Sao Paulo Jaragua', destination: 'Sao Paulo, Brasil', stars: 4 },
  { name: 'Hotel Emiliano Sao Paulo', destination: 'Sao Paulo, Brasil', stars: 5 },
  { name: 'Rosewood Sao Paulo', destination: 'Sao Paulo, Brasil', stars: 5 },
  { name: 'Hyatt Regency Sao Paulo', destination: 'Sao Paulo, Brasil', stars: 4 },
  { name: 'Sheraton Sao Paulo WTC Hotel', destination: 'Sao Paulo, Brasil', stars: 5 },
  { name: 'Radisson Blu Sao Paulo', destination: 'Sao Paulo, Brasil', stars: 4 },
  { name: 'Blue Tree Premium Faria Lima', destination: 'Sao Paulo, Brasil', stars: 4 },
  { name: 'Maksoud Plaza Hotel', destination: 'Sao Paulo, Brasil', stars: 5 },
  // === BRASIL - Salvador ===
  { name: 'Fera Palace Hotel', destination: 'Salvador, Brasil', stars: 5 },
  { name: 'Pestana Convento do Carmo', destination: 'Salvador, Brasil', stars: 5 },
  { name: 'Hotel Fasano Salvador', destination: 'Salvador, Brasil', stars: 5 },
  { name: 'Wish Hotel da Bahia', destination: 'Salvador, Brasil', stars: 4 },
  { name: 'Ibis Salvador Rio Vermelho', destination: 'Salvador, Brasil', stars: 3 },
  { name: 'Uxua Casa Hotel & Spa', destination: 'Trancoso, Brasil', stars: 5 },
  { name: 'Fasano Trancoso', destination: 'Trancoso, Brasil', stars: 5 },
  { name: 'Tivoli Ecoresort Praia do Forte', destination: 'Praia do Forte, Brasil', stars: 5 },
  // === BRASIL - Florianopolis ===
  { name: 'Il Campanario Villaggio Resort', destination: 'Florianopolis, Brasil', stars: 5 },
  { name: 'Costao do Santinho Resort', destination: 'Florianopolis, Brasil', stars: 5 },
  { name: 'Majestic Palace Hotel', destination: 'Florianopolis, Brasil', stars: 5 },
  { name: 'Ponta dos Ganchos Resort', destination: 'Florianopolis, Brasil', stars: 5 },
  { name: 'Novotel Florianopolis', destination: 'Florianopolis, Brasil', stars: 4 },
  // === BRASIL - Recife / Porto de Galinhas ===
  { name: 'Nannai Resort & Spa', destination: 'Porto de Galinhas, Brasil', stars: 5 },
  { name: 'Summerville Beach Resort', destination: 'Porto de Galinhas, Brasil', stars: 5 },
  { name: 'Hotel Armacao', destination: 'Porto de Galinhas, Brasil', stars: 4 },
  { name: 'Mar Hotel Recife', destination: 'Recife, Brasil', stars: 4 },
  // === BRASIL - Fortaleza ===
  { name: 'Gran Marquise Hotel', destination: 'Fortaleza, Brasil', stars: 5 },
  { name: 'Hotel Gran Mareiro', destination: 'Fortaleza, Brasil', stars: 4 },
  { name: 'Seara Praia Hotel', destination: 'Fortaleza, Brasil', stars: 4 },
  // === BRASIL - Brasilia ===
  { name: 'Royal Tulip Brasilia Alvorada', destination: 'Brasilia, Brasil', stars: 5 },
  { name: 'Melia Brasilia', destination: 'Brasilia, Brasil', stars: 4 },
  // === BRASIL - Belo Horizonte ===
  { name: 'Mercure Belo Horizonte Lourdes', destination: 'Belo Horizonte, Brasil', stars: 4 },
  { name: 'Quality Hotel Belo Horizonte', destination: 'Belo Horizonte, Brasil', stars: 3 },
  // === BRASIL - Curitiba ===
  { name: 'Radisson Hotel Curitiba', destination: 'Curitiba, Brasil', stars: 4 },
  { name: 'Four Points by Sheraton Curitiba', destination: 'Curitiba, Brasil', stars: 4 },
  // === BRASIL - Manaus ===
  { name: 'Juma Opera Hotel', destination: 'Manaus, Brasil', stars: 4 },
  { name: 'Tropical Manaus Ecoresort', destination: 'Manaus, Brasil', stars: 4 },
  // === BRASIL - Foz do Iguacu ===
  { name: 'Belmond Hotel das Cataratas', destination: 'Foz do Iguacu, Brasil', stars: 5 },
  { name: 'Wish Foz do Iguacu', destination: 'Foz do Iguacu, Brasil', stars: 4 },
  // === BRASIL - Natal ===
  { name: 'Serhs Natal Grand Hotel', destination: 'Natal, Brasil', stars: 5 },
  { name: 'Wish Natal', destination: 'Natal, Brasil', stars: 4 },
  // === BRASIL - Gramado ===
  { name: 'Hotel Casa da Montanha', destination: 'Gramado, Brasil', stars: 5 },
  { name: 'Buona Vitta Spa & Resort', destination: 'Gramado, Brasil', stars: 4 },
  { name: 'Hotel Laghetto Stilo Centro', destination: 'Gramado, Brasil', stars: 4 },
  { name: 'Colline de France', destination: 'Gramado, Brasil', stars: 5 },
  // === BRASIL - Buzios ===
  { name: 'Casas Brancas Boutique Hotel', destination: 'Buzios, Brasil', stars: 5 },
  { name: 'Insolito Boutique Hotel', destination: 'Buzios, Brasil', stars: 5 },
  // === BRASIL - Other ===
  { name: 'Fasano Angra dos Reis', destination: 'Angra dos Reis, Brasil', stars: 5 },
  { name: 'Hotel Fasano Boa Vista', destination: 'Porto Feliz, Brasil', stars: 5 },
  { name: 'Fasano Jardim Atlantico', destination: 'Itacare, Brasil', stars: 5 },
  { name: 'Kenoa Exclusive Beach Spa & Resort', destination: 'Barra de Sao Miguel, Brasil', stars: 5 },
  { name: 'Txai Resort Itacare', destination: 'Itacare, Brasil', stars: 5 },
  { name: 'Kiaroa Eco-Luxury Resort', destination: 'Marau, Brasil', stars: 5 },
  { name: 'Botanique Hotel & Spa', destination: 'Campos do Jordao, Brasil', stars: 5 },

  // === ESTADOS UNIDOS - New York ===
  { name: 'The Plaza Hotel', destination: 'New York, EUA', stars: 5 },
  { name: 'The Ritz-Carlton New York, Central Park', destination: 'New York, EUA', stars: 5 },
  { name: 'The St. Regis New York', destination: 'New York, EUA', stars: 5 },
  { name: 'Four Seasons Hotel New York Downtown', destination: 'New York, EUA', stars: 5 },
  { name: 'Mandarin Oriental New York', destination: 'New York, EUA', stars: 5 },
  { name: 'The Peninsula New York', destination: 'New York, EUA', stars: 5 },
  { name: 'The Mark Hotel', destination: 'New York, EUA', stars: 5 },
  { name: 'The Carlyle, A Rosewood Hotel', destination: 'New York, EUA', stars: 5 },
  { name: 'Park Hyatt New York', destination: 'New York, EUA', stars: 5 },
  { name: 'Waldorf Astoria New York', destination: 'New York, EUA', stars: 5 },
  { name: 'The Langham New York, Fifth Avenue', destination: 'New York, EUA', stars: 5 },
  { name: 'Hilton Midtown Manhattan', destination: 'New York, EUA', stars: 4 },
  { name: 'Marriott Marquis Times Square', destination: 'New York, EUA', stars: 4 },
  { name: 'The Standard High Line', destination: 'New York, EUA', stars: 4 },
  { name: 'Conrad New York Downtown', destination: 'New York, EUA', stars: 5 },
  { name: 'W New York - Union Square', destination: 'New York, EUA', stars: 4 },
  { name: 'Lotte New York Palace', destination: 'New York, EUA', stars: 5 },
  { name: 'The Pierre, A Taj Hotel', destination: 'New York, EUA', stars: 5 },
  { name: 'JW Marriott Essex House New York', destination: 'New York, EUA', stars: 5 },
  { name: 'InterContinental New York Barclay', destination: 'New York, EUA', stars: 5 },
  { name: 'Aman New York', destination: 'New York, EUA', stars: 5 },
  // === ESTADOS UNIDOS - Miami / South Florida ===
  { name: 'Fontainebleau Miami Beach', destination: 'Miami, EUA', stars: 5 },
  { name: 'The Setai Miami Beach', destination: 'Miami, EUA', stars: 5 },
  { name: 'Hilton Miami Downtown', destination: 'Miami, EUA', stars: 4 },
  { name: 'Four Seasons Hotel at The Surf Club', destination: 'Miami, EUA', stars: 5 },
  { name: 'Faena Hotel Miami Beach', destination: 'Miami, EUA', stars: 5 },
  { name: 'The Edition Miami Beach', destination: 'Miami, EUA', stars: 5 },
  { name: 'Mandarin Oriental Miami', destination: 'Miami, EUA', stars: 5 },
  { name: 'St. Regis Bal Harbour Resort', destination: 'Miami, EUA', stars: 5 },
  { name: 'Acqualina Resort & Residences', destination: 'Miami, EUA', stars: 5 },
  { name: 'W South Beach', destination: 'Miami, EUA', stars: 5 },
  { name: 'Ritz-Carlton South Beach', destination: 'Miami, EUA', stars: 5 },
  { name: '1 Hotel South Beach', destination: 'Miami, EUA', stars: 5 },
  { name: 'Nobu Hotel Miami Beach', destination: 'Miami, EUA', stars: 5 },
  { name: 'The Breakers Palm Beach', destination: 'Palm Beach, EUA', stars: 5 },
  { name: 'Four Seasons Resort Palm Beach', destination: 'Palm Beach, EUA', stars: 5 },
  // === ESTADOS UNIDOS - Los Angeles ===
  { name: 'The Beverly Hills Hotel', destination: 'Los Angeles, EUA', stars: 5 },
  { name: 'Hotel Bel-Air', destination: 'Los Angeles, EUA', stars: 5 },
  { name: 'The Beverly Wilshire', destination: 'Los Angeles, EUA', stars: 5 },
  { name: 'Peninsula Beverly Hills', destination: 'Los Angeles, EUA', stars: 5 },
  { name: 'Waldorf Astoria Beverly Hills', destination: 'Los Angeles, EUA', stars: 5 },
  { name: 'Montage Beverly Hills', destination: 'Los Angeles, EUA', stars: 5 },
  { name: 'Shutters on the Beach', destination: 'Los Angeles, EUA', stars: 5 },
  { name: 'Chateau Marmont', destination: 'Los Angeles, EUA', stars: 5 },
  { name: 'SLS Hotel Beverly Hills', destination: 'Los Angeles, EUA', stars: 5 },
  // === ESTADOS UNIDOS - Las Vegas ===
  { name: 'The Venetian Resort', destination: 'Las Vegas, EUA', stars: 5 },
  { name: 'Bellagio Hotel', destination: 'Las Vegas, EUA', stars: 5 },
  { name: 'Wynn Las Vegas', destination: 'Las Vegas, EUA', stars: 5 },
  { name: 'Encore at Wynn Las Vegas', destination: 'Las Vegas, EUA', stars: 5 },
  { name: 'The Cosmopolitan of Las Vegas', destination: 'Las Vegas, EUA', stars: 5 },
  { name: 'Aria Resort & Casino', destination: 'Las Vegas, EUA', stars: 5 },
  { name: 'MGM Grand Las Vegas', destination: 'Las Vegas, EUA', stars: 5 },
  { name: 'Caesars Palace', destination: 'Las Vegas, EUA', stars: 5 },
  { name: 'Four Seasons Hotel Las Vegas', destination: 'Las Vegas, EUA', stars: 5 },
  // === ESTADOS UNIDOS - Orlando ===
  { name: 'Disney Grand Floridian Resort', destination: 'Orlando, EUA', stars: 5 },
  { name: 'Universal Aventura Hotel', destination: 'Orlando, EUA', stars: 4 },
  { name: 'Hilton Orlando Bonnet Creek', destination: 'Orlando, EUA', stars: 4 },
  { name: 'Four Seasons Resort Orlando', destination: 'Orlando, EUA', stars: 5 },
  { name: 'Waldorf Astoria Orlando', destination: 'Orlando, EUA', stars: 5 },
  { name: 'The Ritz-Carlton Orlando, Grande Lakes', destination: 'Orlando, EUA', stars: 5 },
  { name: 'JW Marriott Orlando', destination: 'Orlando, EUA', stars: 5 },
  // === ESTADOS UNIDOS - Hawaii ===
  { name: 'Four Seasons Resort Maui', destination: 'Maui, EUA', stars: 5 },
  { name: 'Halekulani', destination: 'Honolulu, EUA', stars: 5 },
  { name: 'The Royal Hawaiian', destination: 'Honolulu, EUA', stars: 5 },
  { name: 'Montage Kapalua Bay', destination: 'Maui, EUA', stars: 5 },
  { name: 'Grand Wailea, A Waldorf Astoria Resort', destination: 'Maui, EUA', stars: 5 },
  { name: 'Four Seasons Resort Hualalai', destination: 'Big Island, EUA', stars: 5 },
  { name: 'Mauna Lani, Auberge Resorts Collection', destination: 'Big Island, EUA', stars: 5 },
  // === ESTADOS UNIDOS - San Francisco ===
  { name: 'The Ritz-Carlton San Francisco', destination: 'San Francisco, EUA', stars: 5 },
  { name: 'Four Seasons Hotel San Francisco', destination: 'San Francisco, EUA', stars: 5 },
  { name: 'Fairmont San Francisco', destination: 'San Francisco, EUA', stars: 5 },
  { name: 'The St. Regis San Francisco', destination: 'San Francisco, EUA', stars: 5 },
  // === ESTADOS UNIDOS - Chicago ===
  { name: 'The Peninsula Chicago', destination: 'Chicago, EUA', stars: 5 },
  { name: 'Four Seasons Hotel Chicago', destination: 'Chicago, EUA', stars: 5 },
  { name: 'Waldorf Astoria Chicago', destination: 'Chicago, EUA', stars: 5 },
  { name: 'The Langham Chicago', destination: 'Chicago, EUA', stars: 5 },
  // === ESTADOS UNIDOS - Washington D.C. ===
  { name: 'Four Seasons Hotel Washington D.C.', destination: 'Washington D.C., EUA', stars: 5 },
  { name: 'The Watergate Hotel', destination: 'Washington D.C., EUA', stars: 5 },
  { name: 'Mandarin Oriental Washington D.C.', destination: 'Washington D.C., EUA', stars: 5 },
  { name: 'The Ritz-Carlton Georgetown', destination: 'Washington D.C., EUA', stars: 5 },
  // === ESTADOS UNIDOS - Other ===
  { name: 'The Ritz-Carlton Laguna Niguel', destination: 'Dana Point, EUA', stars: 5 },
  { name: 'Montage Laguna Beach', destination: 'Laguna Beach, EUA', stars: 5 },
  { name: 'Hotel del Coronado', destination: 'San Diego, EUA', stars: 5 },
  { name: 'The Breakers Newport', destination: 'Newport, EUA', stars: 4 },
  { name: 'Rosewood Miramar Beach', destination: 'Montecito, EUA', stars: 5 },
  { name: 'Post Ranch Inn', destination: 'Big Sur, EUA', stars: 5 },
  { name: 'Auberge du Soleil', destination: 'Napa Valley, EUA', stars: 5 },
  { name: 'Meadowood Napa Valley', destination: 'Napa Valley, EUA', stars: 5 },
  { name: 'The Little Nell', destination: 'Aspen, EUA', stars: 5 },
  { name: 'Four Seasons Resort Vail', destination: 'Vail, EUA', stars: 5 },
  { name: 'Montage Deer Valley', destination: 'Park City, EUA', stars: 5 },
  { name: 'Amangiri', destination: 'Canyon Point, EUA', stars: 5 },
  { name: 'The Biltmore Hotel', destination: 'Coral Gables, EUA', stars: 5 },
  { name: 'The Peabody Memphis', destination: 'Memphis, EUA', stars: 4 },
  { name: 'The Adolphus Hotel', destination: 'Dallas, EUA', stars: 5 },
  { name: 'Hotel ZaZa Houston', destination: 'Houston, EUA', stars: 5 },
  { name: 'The Driskill', destination: 'Austin, EUA', stars: 4 },
  { name: 'Four Seasons Resort Scottsdale', destination: 'Scottsdale, EUA', stars: 5 },
  { name: 'The Phoenician', destination: 'Scottsdale, EUA', stars: 5 },
  { name: 'Sanctuary on Camelback Mountain', destination: 'Scottsdale, EUA', stars: 5 },
  { name: 'The Ritz-Carlton Boston', destination: 'Boston, EUA', stars: 5 },
  { name: 'Four Seasons Hotel Boston', destination: 'Boston, EUA', stars: 5 },
  { name: 'Kimpton Hotel Monaco Seattle', destination: 'Seattle, EUA', stars: 4 },
  { name: 'Four Seasons Hotel Seattle', destination: 'Seattle, EUA', stars: 5 },
  { name: 'The Ritz-Carlton Atlanta', destination: 'Atlanta, EUA', stars: 5 },
  { name: 'The Ritz-Carlton Philadelphia', destination: 'Philadelphia, EUA', stars: 5 },

  // === EUROPA - Espanha ===
  { name: 'Hotel Arts Barcelona', destination: 'Barcelona, Espanha', stars: 5 },
  { name: 'W Barcelona', destination: 'Barcelona, Espanha', stars: 5 },
  { name: 'Mandarin Oriental Barcelona', destination: 'Barcelona, Espanha', stars: 5 },
  { name: 'Hotel Casa Fuster', destination: 'Barcelona, Espanha', stars: 5 },
  { name: 'Majestic Hotel & Spa Barcelona', destination: 'Barcelona, Espanha', stars: 5 },
  { name: 'El Palace Barcelona', destination: 'Barcelona, Espanha', stars: 5 },
  { name: 'The One Barcelona', destination: 'Barcelona, Espanha', stars: 5 },
  { name: 'The Westin Palace Madrid', destination: 'Madrid, Espanha', stars: 5 },
  { name: 'Hotel Ritz Madrid', destination: 'Madrid, Espanha', stars: 5 },
  { name: 'Four Seasons Hotel Madrid', destination: 'Madrid, Espanha', stars: 5 },
  { name: 'The Edition Madrid', destination: 'Madrid, Espanha', stars: 5 },
  { name: 'Mandarin Oriental Ritz Madrid', destination: 'Madrid, Espanha', stars: 5 },
  { name: 'Rosewood Villa Magna', destination: 'Madrid, Espanha', stars: 5 },
  { name: 'Hotel Alfonso XIII', destination: 'Sevilha, Espanha', stars: 5 },
  { name: 'Alhambra Palace Hotel', destination: 'Granada, Espanha', stars: 4 },
  { name: 'Hotel Maria Cristina', destination: 'San Sebastian, Espanha', stars: 5 },
  { name: 'Marbella Club Hotel', destination: 'Marbella, Espanha', stars: 5 },
  { name: 'Puente Romano Beach Resort', destination: 'Marbella, Espanha', stars: 5 },
  { name: 'Belmond La Residencia', destination: 'Mallorca, Espanha', stars: 5 },
  { name: 'Park Hyatt Mallorca', destination: 'Mallorca, Espanha', stars: 5 },
  { name: 'Hotel Formentor', destination: 'Mallorca, Espanha', stars: 5 },
  { name: 'The Ritz-Carlton Abama', destination: 'Tenerife, Espanha', stars: 5 },
  { name: 'Royal Hideaway Corales Resort', destination: 'Tenerife, Espanha', stars: 5 },
  { name: 'Gran Hotel Bahia del Duque', destination: 'Tenerife, Espanha', stars: 5 },
  // === EUROPA - Franca ===
  { name: 'Le Meurice', destination: 'Paris, Franca', stars: 5 },
  { name: 'Hotel Plaza Athenee', destination: 'Paris, Franca', stars: 5 },
  { name: 'Shangri-La Hotel Paris', destination: 'Paris, Franca', stars: 5 },
  { name: 'Ibis Paris Montmartre', destination: 'Paris, Franca', stars: 3 },
  { name: 'Novotel Paris Centre Tour Eiffel', destination: 'Paris, Franca', stars: 4 },
  { name: 'Le Bristol Paris', destination: 'Paris, Franca', stars: 5 },
  { name: 'Four Seasons Hotel George V', destination: 'Paris, Franca', stars: 5 },
  { name: 'The Ritz Paris', destination: 'Paris, Franca', stars: 5 },
  { name: 'Park Hyatt Paris-Vendome', destination: 'Paris, Franca', stars: 5 },
  { name: 'Mandarin Oriental Paris', destination: 'Paris, Franca', stars: 5 },
  { name: 'Hotel de Crillon, A Rosewood Hotel', destination: 'Paris, Franca', stars: 5 },
  { name: 'The Peninsula Paris', destination: 'Paris, Franca', stars: 5 },
  { name: 'Le Royal Monceau, Raffles Paris', destination: 'Paris, Franca', stars: 5 },
  { name: 'Prince de Galles', destination: 'Paris, Franca', stars: 5 },
  { name: 'Cheval Blanc Paris', destination: 'Paris, Franca', stars: 5 },
  { name: 'InterContinental Carlton Cannes', destination: 'Cannes, Franca', stars: 5 },
  { name: 'Hotel du Cap-Eden-Roc', destination: 'Antibes, Franca', stars: 5 },
  { name: 'Hotel Negresco Nice', destination: 'Nice, Franca', stars: 5 },
  { name: 'Grand-Hotel du Cap-Ferrat', destination: 'Saint-Jean-Cap-Ferrat, Franca', stars: 5 },
  { name: 'Le Mas Candille', destination: 'Mougins, Franca', stars: 5 },
  { name: 'Les Airelles Courchevel', destination: 'Courchevel, Franca', stars: 5 },
  { name: 'Cheval Blanc Courchevel', destination: 'Courchevel, Franca', stars: 5 },
  { name: 'Chateau de la Messardiere', destination: 'Saint-Tropez, Franca', stars: 5 },
  // === EUROPA - Italia ===
  { name: 'Hotel Hassler Roma', destination: 'Roma, Italia', stars: 5 },
  { name: 'Baglioni Hotel Regina', destination: 'Roma, Italia', stars: 5 },
  { name: 'Hotel de Russie, A Rocco Forte Hotel', destination: 'Roma, Italia', stars: 5 },
  { name: 'The St. Regis Rome', destination: 'Roma, Italia', stars: 5 },
  { name: 'Hotel Eden, Dorchester Collection', destination: 'Roma, Italia', stars: 5 },
  { name: 'Rome Cavalieri, A Waldorf Astoria Hotel', destination: 'Roma, Italia', stars: 5 },
  { name: 'Portrait Roma', destination: 'Roma, Italia', stars: 5 },
  { name: 'Hotel Danieli Venice', destination: 'Veneza, Italia', stars: 5 },
  { name: 'The Gritti Palace', destination: 'Veneza, Italia', stars: 5 },
  { name: 'Belmond Hotel Cipriani', destination: 'Veneza, Italia', stars: 5 },
  { name: 'Aman Venice', destination: 'Veneza, Italia', stars: 5 },
  { name: 'The St. Regis Venice', destination: 'Veneza, Italia', stars: 5 },
  { name: 'Four Seasons Hotel Firenze', destination: 'Florenca, Italia', stars: 5 },
  { name: 'Hotel Savoy Florence', destination: 'Florenca, Italia', stars: 5 },
  { name: 'The St. Regis Florence', destination: 'Florenca, Italia', stars: 5 },
  { name: 'Portrait Firenze', destination: 'Florenca, Italia', stars: 5 },
  { name: 'Belmond Hotel Caruso', destination: 'Costa Amalfitana, Italia', stars: 5 },
  { name: 'Hotel Santa Caterina', destination: 'Costa Amalfitana, Italia', stars: 5 },
  { name: 'Il San Pietro di Positano', destination: 'Positano, Italia', stars: 5 },
  { name: 'Le Sirenuse', destination: 'Positano, Italia', stars: 5 },
  { name: 'Belmond Grand Hotel Timeo', destination: 'Taormina, Italia', stars: 5 },
  { name: 'Capri Palace Jumeirah', destination: 'Capri, Italia', stars: 5 },
  { name: 'Hotel Caesar Augustus', destination: 'Capri, Italia', stars: 5 },
  { name: 'Belmond Hotel Splendido', destination: 'Portofino, Italia', stars: 5 },
  { name: 'Villa d\'Este', destination: 'Lago di Como, Italia', stars: 5 },
  { name: 'Grand Hotel Tremezzo', destination: 'Lago di Como, Italia', stars: 5 },
  { name: 'Mandarin Oriental Lago di Como', destination: 'Lago di Como, Italia', stars: 5 },
  { name: 'Park Hyatt Milan', destination: 'Milao, Italia', stars: 5 },
  { name: 'Bulgari Hotel Milano', destination: 'Milao, Italia', stars: 5 },
  // === EUROPA - Reino Unido ===
  { name: 'The Ritz London', destination: 'Londres, Reino Unido', stars: 5 },
  { name: 'The Savoy', destination: 'Londres, Reino Unido', stars: 5 },
  { name: 'Claridge\'s', destination: 'Londres, Reino Unido', stars: 5 },
  { name: 'Premier Inn London', destination: 'Londres, Reino Unido', stars: 3 },
  { name: 'The Dorchester', destination: 'Londres, Reino Unido', stars: 5 },
  { name: 'Four Seasons Hotel London at Park Lane', destination: 'Londres, Reino Unido', stars: 5 },
  { name: 'The Connaught', destination: 'Londres, Reino Unido', stars: 5 },
  { name: 'The Berkeley', destination: 'Londres, Reino Unido', stars: 5 },
  { name: 'Mandarin Oriental Hyde Park London', destination: 'Londres, Reino Unido', stars: 5 },
  { name: 'Shangri-La The Shard London', destination: 'Londres, Reino Unido', stars: 5 },
  { name: 'The Langham London', destination: 'Londres, Reino Unido', stars: 5 },
  { name: 'Corinthia London', destination: 'Londres, Reino Unido', stars: 5 },
  { name: 'Rosewood London', destination: 'Londres, Reino Unido', stars: 5 },
  { name: 'Brown\'s Hotel, A Rocco Forte Hotel', destination: 'Londres, Reino Unido', stars: 5 },
  { name: 'The Lanesborough', destination: 'Londres, Reino Unido', stars: 5 },
  { name: 'Gleneagles', destination: 'Perthshire, Reino Unido', stars: 5 },
  { name: 'The Balmoral Hotel', destination: 'Edimburgo, Reino Unido', stars: 5 },
  // === EUROPA - Portugal ===
  { name: 'Belmond Reid\'s Palace', destination: 'Funchal, Portugal', stars: 5 },
  { name: 'Four Seasons Hotel Ritz Lisbon', destination: 'Lisboa, Portugal', stars: 5 },
  { name: 'Pestana Palace Lisboa', destination: 'Lisboa, Portugal', stars: 5 },
  { name: 'The Yeatman', destination: 'Porto, Portugal', stars: 5 },
  { name: 'InterContinental Porto', destination: 'Porto, Portugal', stars: 5 },
  { name: 'Bairro Alto Hotel', destination: 'Lisboa, Portugal', stars: 5 },
  { name: 'Penha Longa Resort', destination: 'Sintra, Portugal', stars: 5 },
  { name: 'Pine Cliffs Resort', destination: 'Algarve, Portugal', stars: 5 },
  { name: 'Vila Vita Parc Resort & Spa', destination: 'Algarve, Portugal', stars: 5 },
  { name: 'Conrad Algarve', destination: 'Algarve, Portugal', stars: 5 },
  { name: 'Anantara Vilamoura Algarve Resort', destination: 'Algarve, Portugal', stars: 5 },
  { name: 'Tivoli Avenida Liberdade Lisboa', destination: 'Lisboa, Portugal', stars: 5 },
  { name: 'Six Senses Douro Valley', destination: 'Douro, Portugal', stars: 5 },
  // === EUROPA - Grecia ===
  { name: 'Canaves Oia Suites', destination: 'Santorini, Grecia', stars: 5 },
  { name: 'Grace Hotel Santorini', destination: 'Santorini, Grecia', stars: 5 },
  { name: 'Hotel Grande Bretagne', destination: 'Atenas, Grecia', stars: 5 },
  { name: 'Mystique, A Luxury Collection Hotel', destination: 'Santorini, Grecia', stars: 5 },
  { name: 'Katikies Hotel', destination: 'Santorini, Grecia', stars: 5 },
  { name: 'Andronis Luxury Suites', destination: 'Santorini, Grecia', stars: 5 },
  { name: 'Amanzoe', destination: 'Porto Heli, Grecia', stars: 5 },
  { name: 'Blue Palace Elounda', destination: 'Creta, Grecia', stars: 5 },
  { name: 'Cavo Tagoo Mykonos', destination: 'Mykonos, Grecia', stars: 5 },
  { name: 'Belvedere Hotel Mykonos', destination: 'Mykonos, Grecia', stars: 5 },
  { name: 'Santa Marina, A Luxury Collection Resort', destination: 'Mykonos, Grecia', stars: 5 },
  // === EUROPA - Alemanha ===
  { name: 'Hotel Adlon Kempinski Berlin', destination: 'Berlim, Alemanha', stars: 5 },
  { name: 'The Ritz-Carlton Berlin', destination: 'Berlim, Alemanha', stars: 5 },
  { name: 'Hotel de Rome, A Rocco Forte Hotel', destination: 'Berlim, Alemanha', stars: 5 },
  { name: 'Mandarin Oriental Munich', destination: 'Munique, Alemanha', stars: 5 },
  { name: 'Bayerischer Hof', destination: 'Munique, Alemanha', stars: 5 },
  { name: 'The Charles Hotel, A Rocco Forte Hotel', destination: 'Munique, Alemanha', stars: 5 },
  { name: 'Brenners Park-Hotel & Spa', destination: 'Baden-Baden, Alemanha', stars: 5 },
  { name: 'Fairmont Hotel Vier Jahreszeiten', destination: 'Hamburgo, Alemanha', stars: 5 },
  // === EUROPA - Suica ===
  { name: 'Badrutt\'s Palace Hotel', destination: 'St. Moritz, Suica', stars: 5 },
  { name: 'The Dolder Grand', destination: 'Zurique, Suica', stars: 5 },
  { name: 'Baur au Lac', destination: 'Zurique, Suica', stars: 5 },
  { name: 'Beau-Rivage Palace', destination: 'Lausanne, Suica', stars: 5 },
  { name: 'Victoria-Jungfrau Grand Hotel & Spa', destination: 'Interlaken, Suica', stars: 5 },
  { name: 'The Chedi Andermatt', destination: 'Andermatt, Suica', stars: 5 },
  { name: 'Gstaad Palace', destination: 'Gstaad, Suica', stars: 5 },
  { name: 'Mandarin Oriental Palace Luzern', destination: 'Lucerna, Suica', stars: 5 },
  // === EUROPA - Austria ===
  { name: 'Hotel Sacher Wien', destination: 'Viena, Austria', stars: 5 },
  { name: 'The Ritz-Carlton Vienna', destination: 'Viena, Austria', stars: 5 },
  { name: 'Park Hyatt Vienna', destination: 'Viena, Austria', stars: 5 },
  { name: 'Hotel Imperial Vienna', destination: 'Viena, Austria', stars: 5 },
  // === EUROPA - Holanda ===
  { name: 'Waldorf Astoria Amsterdam', destination: 'Amsterdam, Holanda', stars: 5 },
  { name: 'Conservatorium Hotel', destination: 'Amsterdam, Holanda', stars: 5 },
  { name: 'Hotel de l\'Europe Amsterdam', destination: 'Amsterdam, Holanda', stars: 5 },
  { name: 'InterContinental Amstel Amsterdam', destination: 'Amsterdam, Holanda', stars: 5 },
  // === EUROPA - Turquia ===
  { name: 'Four Seasons Hotel Istanbul at Sultanahmet', destination: 'Istanbul, Turquia', stars: 5 },
  { name: 'Ciragan Palace Kempinski Istanbul', destination: 'Istanbul, Turquia', stars: 5 },
  { name: 'Raffles Istanbul', destination: 'Istanbul, Turquia', stars: 5 },
  { name: 'Mandarin Oriental Bodrum', destination: 'Bodrum, Turquia', stars: 5 },
  // === EUROPA - Croacia ===
  { name: 'Hotel Excelsior Dubrovnik', destination: 'Dubrovnik, Croacia', stars: 5 },
  { name: 'Sun Gardens Dubrovnik', destination: 'Dubrovnik, Croacia', stars: 5 },
  // === EUROPA - Noruega / Suecia ===
  { name: 'Grand Hotel Oslo', destination: 'Oslo, Noruega', stars: 5 },
  { name: 'Grand Hotel Stockholm', destination: 'Estocolmo, Suecia', stars: 5 },
  { name: 'Hotel Norrmalm, Nobis Group', destination: 'Estocolmo, Suecia', stars: 5 },

  // === ASIA ===
  { name: 'The Peninsula Tokyo', destination: 'Toquio, Japao', stars: 5 },
  { name: 'Aman Tokyo', destination: 'Toquio, Japao', stars: 5 },
  { name: 'Park Hyatt Tokyo', destination: 'Toquio, Japao', stars: 5 },
  { name: 'Marina Bay Sands', destination: 'Singapura', stars: 5 },
  { name: 'Raffles Hotel Singapore', destination: 'Singapura', stars: 5 },
  { name: 'The Peninsula Bangkok', destination: 'Bangkok, Tailandia', stars: 5 },
  { name: 'Mandarin Oriental Bangkok', destination: 'Bangkok, Tailandia', stars: 5 },
  { name: 'Taj Mahal Palace', destination: 'Mumbai, India', stars: 5 },
  // === ORIENTE MEDIO ===
  { name: 'Burj Al Arab', destination: 'Dubai, Emirados Arabes', stars: 5 },
  { name: 'Atlantis The Palm', destination: 'Dubai, Emirados Arabes', stars: 5 },
  { name: 'Armani Hotel Dubai', destination: 'Dubai, Emirados Arabes', stars: 5 },
  // === AMERICA LATINA ===
  { name: 'Four Seasons Hotel Buenos Aires', destination: 'Buenos Aires, Argentina', stars: 5 },
  { name: 'Alvear Palace Hotel', destination: 'Buenos Aires, Argentina', stars: 5 },
  { name: 'Hotel Noi Santiago', destination: 'Santiago, Chile', stars: 5 },
  { name: 'The Ritz-Carlton Santiago', destination: 'Santiago, Chile', stars: 5 },
  { name: 'Hyatt Regency Cancun', destination: 'Cancun, Mexico', stars: 5 },
  { name: 'Secrets The Vine Cancun', destination: 'Cancun, Mexico', stars: 5 },
  { name: 'Hotel Nayara Springs', destination: 'Arenal, Costa Rica', stars: 5 },
  // === CARIBE ===
  { name: 'Sandals Royal Barbados', destination: 'Barbados', stars: 5 },
  { name: 'The Ritz-Carlton Grand Cayman', destination: 'Ilhas Cayman', stars: 5 },
  { name: 'Anse Chastanet Resort', destination: 'Santa Lucia', stars: 5 },
  // === AFRICA ===
  { name: 'One&Only Cape Town', destination: 'Cidade do Cabo, Africa do Sul', stars: 5 },
  { name: 'The Table Bay Hotel', destination: 'Cidade do Cabo, Africa do Sul', stars: 5 },
  // === OCEANIA ===
  { name: 'Park Hyatt Sydney', destination: 'Sydney, Australia', stars: 5 },
  { name: 'The Langham Melbourne', destination: 'Melbourne, Australia', stars: 5 },
  // === MALDIVAS ===
  { name: 'Soneva Fushi', destination: 'Maldivas', stars: 5 },
  { name: 'Conrad Maldives Rangali Island', destination: 'Maldivas', stars: 5 },
  { name: 'One&Only Reethi Rah', destination: 'Maldivas', stars: 5 },
];
